# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
skip_docs

fastlane_require 'dotenv'

default_platform(:ios)

platform :ios do
  lane :alpha do
    Dotenv.overload '../../.env.production'
    puts 'LOADED ENV: ' + ENV['ENVIRONMENT']    

    increment_version_number(
      version_number: load_json(json_path: "../package.json")["version"],      
    )

    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
    )

    increment_build_number(
      build_number: latest_testflight_build_number(
        username: ENV['APPLE_ID_USERNAME']
      ) + 1,
    )    

    sync_code_signing(
      type: "appstore",
      readonly: true,
      username: ENV['APPLE_ID_USERNAME']
    )
    
    build_app(
      scheme: "Habit", 
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.anlitz.habit" => "match AppStore com.anlitz.habit",
        }
      }
    )    

    upload_to_testflight(      
      skip_waiting_for_build_processing: true,
    )
  end

  lane :certificate do |options|
    Dotenv.overload '../../.env.production'
    puts 'LOADED ENV: ' + ENV['ENVIRONMENT']    
    
    sync_code_signing(
      type: options[:type] || 'development',
      readonly: options[:write] || false,
      username: ENV['APPLE_ID_USERNAME']
    )  
  end
end
