name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup env
        run: |
          git fetch origin $GITHUB_BASE_REF

      - uses: actions/setup-node@v2

      - name: Setup NPM
        run: |
          # using anything above this version will cause npm install to fail
          # due to possible Conflicting peer dependency
          npm i -g npm@8.5.5

      - name: Install Dependencies
        run: npm ci

      - name: Install app node modules
        run: |
          npx nx ensure-symlink

      - name: Typescript Compile
        run: |
          npm run type-check -- --base=origin/$GITHUB_BASE_REF

      - name: Run lint
        run: |
          npm run lint -- --base=origin/$GITHUB_BASE_REF
